// The markets we watch. Shared by the browser page and the daily build script.
// side: "West" = Americas + Europe + Africa, "East" = Asia + Oceania (incl. Middle East).
// iso: ISO 3166 numeric code, used to color the world map. at: [lon, lat] for the map marker.
// kind: index | bond | stock | sector | macro.
// Bonds are tracked through bond ETF prices, so a 2d bar = bond prices falling (yields rising).

export const COUNTRIES = {
  US: { name: "United States", iso: "840", side: "West", flag: "🇺🇸", at: [-98.5, 39.8] },
  CA: { name: "Canada", iso: "124", side: "West", flag: "🇨🇦", at: [-106, 56] },
  MX: { name: "Mexico", iso: "484", side: "West", flag: "🇲🇽", at: [-102, 23.6] },
  BR: { name: "Brazil", iso: "076", side: "West", flag: "🇧🇷", at: [-51.9, -14.2] },
  AR: { name: "Argentina", iso: "032", side: "West", flag: "🇦🇷", at: [-63.6, -38.4] },
  CL: { name: "Chile", iso: "152", side: "West", flag: "🇨🇱", at: [-71.5, -35.7] },
  GB: { name: "United Kingdom", iso: "826", side: "West", flag: "🇬🇧", at: [-1.5, 52.5] },
  DE: { name: "Germany", iso: "276", side: "West", flag: "🇩🇪", at: [10.4, 51.2] },
  FR: { name: "France", iso: "250", side: "West", flag: "🇫🇷", at: [2.2, 46.6] },
  IT: { name: "Italy", iso: "380", side: "West", flag: "🇮🇹", at: [12.6, 42.5] },
  ES: { name: "Spain", iso: "724", side: "West", flag: "🇪🇸", at: [-3.7, 40.4] },
  NL: { name: "Netherlands", iso: "528", side: "West", flag: "🇳🇱", at: [5.3, 52.1] },
  CH: { name: "Switzerland", iso: "756", side: "West", flag: "🇨🇭", at: [8.2, 46.8] },
  SE: { name: "Sweden", iso: "752", side: "West", flag: "🇸🇪", at: [15.0, 60.1] },
  DK: { name: "Denmark", iso: "208", side: "West", flag: "🇩🇰", at: [9.5, 56.3] },
  BE: { name: "Belgium", iso: "056", side: "West", flag: "🇧🇪", at: [4.5, 50.5] },
  AT: { name: "Austria", iso: "040", side: "West", flag: "🇦🇹", at: [14.6, 47.5] },
  PL: { name: "Poland", iso: "616", side: "West", flag: "🇵🇱", at: [19.1, 51.9] },
  NO: { name: "Norway", iso: "578", side: "West", flag: "🇳🇴", at: [8.5, 60.5] },
  ZA: { name: "South Africa", iso: "710", side: "West", flag: "🇿🇦", at: [22.9, -30.6] },
  JP: { name: "Japan", iso: "392", side: "East", flag: "🇯🇵", at: [138.3, 36.2] },
  CN: { name: "China", iso: "156", side: "East", flag: "🇨🇳", at: [104.2, 35.9] },
  HK: { name: "Hong Kong", iso: "344", side: "East", flag: "🇭🇰", at: [114.2, 22.3] },
  IN: { name: "India", iso: "356", side: "East", flag: "🇮🇳", at: [78.9, 21.0] },
  KR: { name: "South Korea", iso: "410", side: "East", flag: "🇰🇷", at: [127.8, 35.9] },
  TW: { name: "Taiwan", iso: "158", side: "East", flag: "🇹🇼", at: [121.0, 23.7] },
  AU: { name: "Australia", iso: "036", side: "East", flag: "🇦🇺", at: [133.8, -25.3] },
  NZ: { name: "New Zealand", iso: "554", side: "East", flag: "🇳🇿", at: [174.9, -40.9] },
  SG: { name: "Singapore", iso: "702", side: "East", flag: "🇸🇬", at: [103.8, 1.35] },
  ID: { name: "Indonesia", iso: "360", side: "East", flag: "🇮🇩", at: [113.9, -0.8] },
  MY: { name: "Malaysia", iso: "458", side: "East", flag: "🇲🇾", at: [101.98, 4.2] },
  TH: { name: "Thailand", iso: "764", side: "East", flag: "🇹🇭", at: [100.99, 15.87] },
  PH: { name: "Philippines", iso: "608", side: "East", flag: "🇵🇭", at: [121.77, 12.88] },
  SA: { name: "Saudi Arabia", iso: "682", side: "East", flag: "🇸🇦", at: [45.1, 23.9] },
  IL: { name: "Israel", iso: "376", side: "East", flag: "🇮🇱", at: [34.85, 31.05] },
  TR: { name: "Turkey", iso: "792", side: "East", flag: "🇹🇷", at: [35.2, 39.0] },
  GLOBAL: { name: "Global", iso: null, side: null, flag: "🌐" },
};

const m = (symbol, name, country, kind) => ({ symbol, name, country, kind });

export const MARKETS = [
  // Stock indices
  m("^GSPC", "S&P 500", "US", "index"),
  m("^NDX", "Nasdaq 100", "US", "index"),
  m("^DJI", "Dow Jones", "US", "index"),
  m("^RUT", "Russell 2000", "US", "index"),
  m("^GSPTSE", "TSX Composite", "CA", "index"),
  m("^MXX", "IPC Mexico", "MX", "index"),
  m("^BVSP", "Bovespa", "BR", "index"),
  m("^MERV", "Merval", "AR", "index"),
  m("ECH", "Chile (MSCI ETF)", "CL", "index"),
  m("^FTSE", "FTSE 100", "GB", "index"),
  m("^GDAXI", "DAX", "DE", "index"),
  m("^FCHI", "CAC 40", "FR", "index"),
  m("FTSEMIB.MI", "FTSE MIB", "IT", "index"),
  m("^IBEX", "IBEX 35", "ES", "index"),
  m("^AEX", "AEX", "NL", "index"),
  m("^SSMI", "SMI", "CH", "index"),
  m("^OMX", "OMX Stockholm 30", "SE", "index"),
  m("^OMXC25", "OMX Copenhagen 25", "DK", "index"),
  m("^BFX", "BEL 20", "BE", "index"),
  m("^ATX", "ATX", "AT", "index"),
  m("EPOL", "Poland (MSCI ETF)", "PL", "index"),
  m("NORW", "Norway (MSCI ETF)", "NO", "index"),
  m("^J203.JO", "JSE All Share", "ZA", "index"),
  m("^N225", "Nikkei 225", "JP", "index"),
  m("000001.SS", "Shanghai Composite", "CN", "index"),
  m("^HSI", "Hang Seng", "HK", "index"),
  m("^NSEI", "Nifty 50", "IN", "index"),
  m("^KS11", "KOSPI", "KR", "index"),
  m("^TWII", "Taiwan Weighted", "TW", "index"),
  m("^AXJO", "ASX 200", "AU", "index"),
  m("^NZ50", "NZX 50", "NZ", "index"),
  m("^STI", "Straits Times", "SG", "index"),
  m("^JKSE", "Jakarta Composite", "ID", "index"),
  m("^KLSE", "KLCI", "MY", "index"),
  m("THD", "Thailand (MSCI ETF)", "TH", "index"),
  m("EPHE", "Philippines (MSCI ETF)", "PH", "index"),
  m("KSA", "Saudi Arabia (MSCI ETF)", "SA", "index"),
  m("TA35.TA", "TA-35", "IL", "index"),
  m("XU100.IS", "BIST 100", "TR", "index"),

  // Government bonds (bond ETF prices)
  m("TLT", "US Treasuries 20+ yr", "US", "bond"),
  m("IEF", "US Treasuries 7-10 yr", "US", "bond"),
  m("XGB.TO", "Canada Govt Bonds", "CA", "bond"),
  m("IGLT.L", "UK Gilts", "GB", "bond"),
  m("EXX6.DE", "German Bunds 10+ yr", "DE", "bond"),
  m("2561.T", "Japan Govt Bonds", "JP", "bond"),
  m("BTP10.MI", "Italy BTP 10 yr", "IT", "bond"),
  m("148070.KS", "Korea Treasury 10 yr", "KR", "bond"),
  m("LTGILTBEES.NS", "India Govt Bonds 8-13 yr", "IN", "bond"),
  m("IMAB11.SA", "Brazil Inflation-Linked Govt Bonds", "BR", "bond"),
  m("CBON", "China Bonds", "CN", "bond"),
  m("IGB.AX", "Australia Govt Bonds", "AU", "bond"),
  m("EMB", "Emerging Mkt Bonds (USD)", "GLOBAL", "bond"),
  m("BWX", "Intl Govt Bonds", "GLOBAL", "bond"),

  // Global sectors (iShares Global sector ETFs)
  m("IXN", "Technology", "GLOBAL", "sector"),
  m("IXG", "Financials", "GLOBAL", "sector"),
  m("IXC", "Energy", "GLOBAL", "sector"),
  m("IXJ", "Healthcare", "GLOBAL", "sector"),
  m("EXI", "Industrials", "GLOBAL", "sector"),
  m("RXI", "Consumer Discretionary", "GLOBAL", "sector"),
  m("KXI", "Consumer Staples", "GLOBAL", "sector"),
  m("JXI", "Utilities", "GLOBAL", "sector"),
  m("MXI", "Materials", "GLOBAL", "sector"),
  m("IXP", "Communication", "GLOBAL", "sector"),
  m("REET", "Real Estate", "GLOBAL", "sector"),

  // Major stocks
  m("AAPL", "Apple", "US", "stock"),
  m("MSFT", "Microsoft", "US", "stock"),
  m("NVDA", "Nvidia", "US", "stock"),
  m("AMZN", "Amazon", "US", "stock"),
  m("GOOGL", "Alphabet", "US", "stock"),
  m("META", "Meta", "US", "stock"),
  m("TSLA", "Tesla", "US", "stock"),
  m("JPM", "JPMorgan", "US", "stock"),
  m("2330.TW", "TSMC", "TW", "stock"),
  m("005930.KS", "Samsung", "KR", "stock"),
  m("7203.T", "Toyota", "JP", "stock"),
  m("6758.T", "Sony", "JP", "stock"),
  m("0700.HK", "Tencent", "HK", "stock"),
  m("9988.HK", "Alibaba", "HK", "stock"),
  m("RELIANCE.NS", "Reliance", "IN", "stock"),
  m("HDFCBANK.NS", "HDFC Bank", "IN", "stock"),
  m("ASML.AS", "ASML", "NL", "stock"),
  m("SAP.DE", "SAP", "DE", "stock"),
  m("MC.PA", "LVMH", "FR", "stock"),
  m("NESN.SW", "Nestlé", "CH", "stock"),
  m("NOVO-B.CO", "Novo Nordisk", "DK", "stock"),
  m("SHEL.L", "Shell", "GB", "stock"),
  m("AZN.L", "AstraZeneca", "GB", "stock"),
  m("HSBA.L", "HSBC", "GB", "stock"),
  m("2222.SR", "Saudi Aramco", "SA", "stock"),
  m("BHP.AX", "BHP", "AU", "stock"),
  m("RY.TO", "Royal Bank of Canada", "CA", "stock"),
  m("PETR4.SA", "Petrobras", "BR", "stock"),

  // Macro gauges
  m("GC=F", "Gold", "GLOBAL", "macro"),
  m("CL=F", "Crude Oil", "GLOBAL", "macro"),
  m("HG=F", "Copper", "GLOBAL", "macro"),
  m("DX-Y.NYB", "US Dollar", "GLOBAL", "macro"),
  m("BTC-USD", "Bitcoin", "GLOBAL", "macro"),
];
